apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-monitoring
  namespace: rabbitmq-system
spec:
  template:
    spec:
      containers:
      - name: rabbitmq-monitoring
        image: python:3.8-slim-buster
        command: ["/bin/bash", "-c"]
        args:
        - |
          apt-get update && apt-get install -y wget
          https://raw.githubusercontent.com/shaN480/positive/main/rabbitmq.py        
          python rabbitmq.py --host=<RABBITMQ_HOST> --port=15672 --username=test --password=test
      restartPolicy: Never

      ---

apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-pod
  namespace: rabbitmq-system
spec:
  containers:
  - name: rabbitmq-container
    image: python:3.9
    command: ["python3", "rabbitmq.py", "--host=<RABBITMQ_HOST>", "--port=<RABBITMQ_PORT>", "--username=<RABBITMQ_USERNAME>", "--password=<RABBITMQ_PASSWORD>"]
    volumeMounts:
    - name: rabbitmq-volume
      mountPath: /opt/site24x7/monagent/plugins/rabbitmq/
  volumes:
  - name: rabbitmq-volume
    hostPath:
      path: /opt/site24x7/monagent/plugins/rabbitmq/
      type: DirectoryOrCreate
  initContainers:
  - name: mount-path
    image: busybox
    command: ["sh", "-c", "mkdir -p /opt/site24x7/monagent/plugins/rabbitmq/"]
    volumeMounts:
    - name: rabbitmq-volume
      mountPath: /opt/site24x7/monagent/plugins/rabbitmq/
  - name: download-rabbitmq-files
    image: busybox
    command: ["sh", "-c", "wget https://raw.githubusercontent.com/shaN480/positive/main/rabbitmq.py -O /opt/site24x7/monagent/plugins/rabbitmq/rabbitmq.py"]
    volumeMounts:
    - name: rabbitmq-volume
      mountPath: /opt/site24x7/monagent/plugins/rabbitmq/

